<?php

class EMAIL_STATUS {
    const NORMAL = 1;
    const WAITING_FOR_INVITATION_EMAIL = 2;
    const INVITATION_EMAIL_ALREADY_SENT = 3;
    const WAITING_FOR_SCHEDULE_CHANGE_EMAIL = 4;
    const SCHEDULE_CHANGE_EMAIL_ALREADY_SENT = 5;
};

